/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author natal
 */
public class SigIn extends javax.swing.JFrame {

    /**
     * Creates new form SigIn
     */
    public SigIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSigIn = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jTextFieldSurName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTextFieldPostalCode = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jTextFieldCity = new javax.swing.JTextField();
        kButtonFinished = new keeptoo.KButton();
        kButtonCancel = new keeptoo.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelImageBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSigIn.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.setOpaque(false);
        jPanelSigIn.setPreferredSize(new java.awt.Dimension(471, 554));
        jPanelSigIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 360, 10));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 360, 10));

        jTextFieldSurName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jTextFieldSurName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSurName.setText("Apellido");
        jTextFieldSurName.setBorder(null);
        jTextFieldSurName.setOpaque(false);
        jTextFieldSurName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSurNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldSurNameMouseExited(evt);
            }
        });
        jPanelSigIn.add(jTextFieldSurName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 360, 40));

        jTextFieldEmail.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setText("Correo electrónico");
        jTextFieldEmail.setBorder(null);
        jTextFieldEmail.setOpaque(false);
        jTextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMouseExited(evt);
            }
        });
        jPanelSigIn.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 360, 40));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 360, 10));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 10));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresá tus datos");
        jPanelSigIn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 290, 50));

        jTextFieldCountry.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jTextFieldCountry.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCountry.setText("País");
        jTextFieldCountry.setBorder(null);
        jTextFieldCountry.setOpaque(false);
        jTextFieldCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldCountryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldCountryMouseExited(evt);
            }
        });
        jTextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountryActionPerformed(evt);
            }
        });
        jPanelSigIn.add(jTextFieldCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 360, 40));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 360, 10));

        jTextFieldPostalCode.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jTextFieldPostalCode.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPostalCode.setText("Codigo postal");
        jTextFieldPostalCode.setBorder(null);
        jTextFieldPostalCode.setOpaque(false);
        jTextFieldPostalCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldPostalCodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldPostalCodeMouseExited(evt);
            }
        });
        jTextFieldPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPostalCodeActionPerformed(evt);
            }
        });
        jPanelSigIn.add(jTextFieldPostalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 130, 40));

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 360, 10));

        jTextFieldCity.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jTextFieldCity.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCity.setText("Ciudad");
        jTextFieldCity.setBorder(null);
        jTextFieldCity.setOpaque(false);
        jTextFieldCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldCityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldCityMouseExited(evt);
            }
        });
        jTextFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCityActionPerformed(evt);
            }
        });
        jPanelSigIn.add(jTextFieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 220, 40));

        kButtonFinished.setText("Listo");
        kButtonFinished.setBorderPainted(false);
        kButtonFinished.setFont(new java.awt.Font("Segoe UI Light", 0, 26)); // NOI18N
        kButtonFinished.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButtonFinished.setkBorderRadius(50);
        kButtonFinished.setkEndColor(new java.awt.Color(121, 213, 215));
        kButtonFinished.setkHoverEndColor(new java.awt.Color(61, 255, 255));
        kButtonFinished.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButtonFinished.setkHoverStartColor(new java.awt.Color(0, 198, 198));
        kButtonFinished.setkPressedColor(new java.awt.Color(255, 0, 0));
        kButtonFinished.setkSelectedColor(new java.awt.Color(77, 141, 169));
        kButtonFinished.setkStartColor(new java.awt.Color(0, 132, 132));
        kButtonFinished.setOpaque(false);
        kButtonFinished.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButtonFinishedMouseClicked(evt);
            }
        });
        jPanelSigIn.add(kButtonFinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 150, -1));

        kButtonCancel.setText("Cancelar");
        kButtonCancel.setBorderPainted(false);
        kButtonCancel.setFont(new java.awt.Font("Segoe UI Light", 0, 26)); // NOI18N
        kButtonCancel.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButtonCancel.setkBorderRadius(50);
        kButtonCancel.setkEndColor(new java.awt.Color(121, 213, 215));
        kButtonCancel.setkHoverEndColor(new java.awt.Color(61, 255, 255));
        kButtonCancel.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButtonCancel.setkHoverStartColor(new java.awt.Color(0, 198, 198));
        kButtonCancel.setkPressedColor(new java.awt.Color(255, 0, 0));
        kButtonCancel.setkSelectedColor(new java.awt.Color(77, 141, 169));
        kButtonCancel.setkStartColor(new java.awt.Color(0, 132, 132));
        kButtonCancel.setOpaque(false);
        kButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButtonCancelMouseClicked(evt);
            }
        });
        jPanelSigIn.add(kButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 150, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelSigIn.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 10, 40));

        jTextFieldName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldName.setText("Nombre");
        jTextFieldName.setBorder(null);
        jTextFieldName.setOpaque(false);
        jTextFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseExited(evt);
            }
        });
        jPanelSigIn.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 360, 40));

        jTextFieldAge.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jTextFieldAge.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldAge.setText("Edad");
        jTextFieldAge.setBorder(null);
        jTextFieldAge.setOpaque(false);
        jTextFieldAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldAgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldAgeMouseExited(evt);
            }
        });
        jPanelSigIn.add(jTextFieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, 40));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSigIn.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 360, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelSigIn.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 20, 60));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseExited(evt);
            }
        });
        jPanelSigIn.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 360, 40));

        jLabelImageBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/fondoLogin.jpg"))); // NOI18N
        jPanelSigIn.add(jLabelImageBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelSigIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelSigIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCountryActionPerformed

    private void jTextFieldPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPostalCodeActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCityActionPerformed

    private void kButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButtonCancelMouseClicked
        // loadComponentList();

        /*for(int i=0;i<(components.length-1);i++){ //en menos uno porque el label de fondo es el ultimo componente
            jPanelBack.remove(components[i]);

        }*/

        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_kButtonCancelMouseClicked

    private void jTextFieldNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseEntered
        GraphicControl.animationJTextField(60, (60-9), 10, 1, jTextFieldName, 1);
    }//GEN-LAST:event_jTextFieldNameMouseEntered

    private void jTextFieldNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseExited
        GraphicControl.animationJTextField((60-9), 60, 10, 1, jTextFieldName, 2);
    }//GEN-LAST:event_jTextFieldNameMouseExited

    private void jTextFieldSurNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSurNameMouseEntered
        GraphicControl.animationJTextField(120, (120-9), 10, 1, jTextFieldSurName, 1);
    }//GEN-LAST:event_jTextFieldSurNameMouseEntered

    private void jTextFieldSurNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSurNameMouseExited
        GraphicControl.animationJTextField((120-9), 120, 10, 1, jTextFieldSurName, 2);
    }//GEN-LAST:event_jTextFieldSurNameMouseExited

    private void jTextFieldEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMouseEntered
        GraphicControl.animationJTextField(180, (180-9), 10, 1, jTextFieldEmail, 1);
    }//GEN-LAST:event_jTextFieldEmailMouseEntered

    private void jTextFieldEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMouseExited
        GraphicControl.animationJTextField((180-9), 180, 10, 1, jTextFieldEmail, 2);
    }//GEN-LAST:event_jTextFieldEmailMouseExited

    private void jTextFieldAgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAgeMouseEntered
        GraphicControl.animationJTextField(300, (300-9), 10, 1, jTextFieldAge, 1);
    }//GEN-LAST:event_jTextFieldAgeMouseEntered

    private void jTextFieldAgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAgeMouseExited
        GraphicControl.animationJTextField((300-9), 300, 10, 1, jTextFieldAge, 2);
    }//GEN-LAST:event_jTextFieldAgeMouseExited

    private void jTextFieldCountryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCountryMouseEntered
        GraphicControl.animationJTextField(360, (360-9), 10, 1, jTextFieldCountry, 1);
    }//GEN-LAST:event_jTextFieldCountryMouseEntered

    private void jTextFieldCountryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCountryMouseExited
        GraphicControl.animationJTextField((360-9), 360, 10, 1, jTextFieldCountry, 2);
    }//GEN-LAST:event_jTextFieldCountryMouseExited

    private void jTextFieldCityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCityMouseEntered
        GraphicControl.animationJTextField(420, (420-9), 10, 1, jTextFieldCity, 1);
    }//GEN-LAST:event_jTextFieldCityMouseEntered

    private void jTextFieldCityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCityMouseExited
        GraphicControl.animationJTextField((420-9), 420, 10, 1, jTextFieldCity, 2);
    }//GEN-LAST:event_jTextFieldCityMouseExited

    private void jTextFieldPostalCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPostalCodeMouseEntered
        GraphicControl.animationJTextField(420, (420-9), 10, 1, jTextFieldPostalCode, 1);
    }//GEN-LAST:event_jTextFieldPostalCodeMouseEntered

    private void jTextFieldPostalCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPostalCodeMouseExited
        GraphicControl.animationJTextField((420-9), 420, 10, 1, jTextFieldPostalCode, 2);
    }//GEN-LAST:event_jTextFieldPostalCodeMouseExited

    private void kButtonFinishedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButtonFinishedMouseClicked
        // aca se crearia un cliente...si tuviera uno
    }//GEN-LAST:event_kButtonFinishedMouseClicked

    private void jPasswordField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseEntered
        GraphicControl.animationJTextField(240, (240-9), 10, 1, jPasswordField1, 1);
    }//GEN-LAST:event_jPasswordField1MouseEntered

    private void jPasswordField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseExited
        GraphicControl.animationJTextField((240-9), 240, 10, 1, jPasswordField1, 2);
    }//GEN-LAST:event_jPasswordField1MouseExited

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SigIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImageBack;
    private javax.swing.JPanel jPanelSigIn;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPostalCode;
    private javax.swing.JTextField jTextFieldSurName;
    private keeptoo.KButton kButtonCancel;
    private keeptoo.KButton kButtonFinished;
    // End of variables declaration//GEN-END:variables
}
